version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    environment: 
     - REACT_APP_BACKEND_URL=api/
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy

  fronend:
    image: hello-front-prod
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: hello-front-prod

  server:
    image: todo-back-prod
    environment: 
    - REDIS_URL=//redis
    - MONGO_URL=mongodb://the_username:the_password@mongo/the_database
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    container_name: todo-back-prod

  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  redis:
    image: redis
    ports: 
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes: # Declare the volume
      - ./todo-backend/redis_data:/data
  
  